version: "3.8"
services:
  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@123
      - MYSQL_DATABASE=login_system
  login-app:
    image: login-app
    ports:
      - "8080:8080"
    environment:
      db.host: "mysqldb"
      db.port: "3306"
      db.name: "login_system"
      db.user: "root"
      db.password: "Mysql@123"
    depends_on:
      - mysqldb